### ISSUE TITLE
`ParseKeyFromURL` Is missing some of the helper functions for fields.

### ISSUE THREAD

**Issue by s3rj1k** [cristalhq/otp#15]
ParseKeyFromURL Is missing some of the helper functions for fields, refs below:
- https://github.com/google/google-authenticator/wiki/Key-Uri-Format#counter
- https://github.com/google/google-authenticator/wiki/Key-Uri-Format#algorithm
- https://github.com/google/google-authenticator/wiki/Key-Uri-Format#digits

Would be nice to have them all and use `Key` object as a building block for `TOTPConfig`/`HOTPConfig`

**Comment by cristaloleg** [comment]
Hey, wanna make a PR ?

**Comment by s3rj1k** [comment]
> Hey, wanna make a PR ?

Yea, a bit later hopefully today

**Comment by s3rj1k** [comment]
@cristaloleg Go merge ?)

**Comment by cristaloleg** [comment]
Hah, started reviewing 2 mins ago. Give a sec.
