### ISSUE TITLE
Possible secret leak into error from `url.Parse`.

### ISSUE THREAD

**Issue by s3rj1k** [cristalhq/otp#20]
Possible secret leak into error from `url.Parse`.

https://github.com/cristalhq/otp/blob/main/otp.go#L79

In case of invalid url `url.Parse` returns error with full string in it, that can leak OTP secret into logs.

This either should be highlighted in docs or plugged-in with custom error messages instead of the one that comes from `url.Parse`.

Redacted example of error
```
parse "otpauth://totp/user@domain.com:00000000-0000-0000-0000-000000000000?digits=6&secret=***&period=30&algorithm=SHA1&issuer=user%40domain.com\n": net/url: invalid control character in URL
```

**Comment by cristaloleg** [comment]
Sounds like this is the simplest fix https://github.com/golang/go/issues/53993#issuecomment-1488889449

Feel free to send a PR.

**Comment by s3rj1k** [comment]
> simplest fix

Custom error or documentation?

**Comment by cristaloleg** [comment]
Custom error sounds better (not everyone reads docs and understand problem with `url.Parse`, well, I coded with this bug 🤷 )

**Comment by cristaloleg** [comment]
Also, we've https://pkg.go.dev/net/url#URL.Redacted which can be used in error message text.

**Comment by s3rj1k** [comment]
> [URL.Redacted](https://pkg.go.dev/net/url#URL.Redacted)

In my use-case it seems that issuer is also leaking some personal info like email, so if redacting issuer and domain also needs to be hidden. (Makes a bit more complicated).
